namespace BolaoTeste.Dto.ListarPalpite
{
    public class ListarPalpiteResponse
    {
        public string Usuario { get; set; }
        public int Qatar { get; set; }
        public int Equador { get; set; }
        public int Senegal { get; set; }
        public int Holanda { get; set; }
        public int QatarPontos { get; set; }
        public int EquadorPontos { get; set; }
        public int SenegalPontos { get; set; }
        public int HolandaPontos { get; set; }
        public int Inglaterra { get; set; }
        public int Iram { get; set; }
        public int USA { get; set; }
        public int PaisDeGales { get; set; }
        public int InglaterraPontos { get; set; }
        public int IramPontos { get; set; }
        public int USAPontos { get; set; }
        public int PaisDeGalesPontos { get; set; }
        public int Argentina { get; set; }
        public int ArabiaSaudita { get; set; }
        public int Mexico { get; set; }
        public int Polonia { get; set; }
        public int Franca { get; set; }
        public int Australia { get; set; }
        public int Dinamarca { get; set; }
        public int Tunisia { get; set; }
        public int FrancaPontos { get; set; }
        public int AustraliaPontos { get; set; }
        public int DinamarcaPontos { get; set; }
        public int TunisiaPontos { get; set; }
        public int ArgentinaPontos { get; set; }
        public int ArabiaSauditaPontos { get; set; }
        public int MexicoPontos { get; set; }
        public int PoloniaPontos { get; set; }
        public int Espanha { get; set; }
        public int CostaRica { get; set; }
        public int Alemanha { get; set; }
        public int Japao { get; set; }
        public int EspanhaPontos { get; set; }
        public int CostaRicaPontos { get; set; }
        public int AlemanhaPontos { get; set; }
        public int JapaoPontos { get; set; }
        public int Belgica { get; set; }
        public int Canada { get; set; }
        public int Marrocos { get; set; }
        public int Croacia { get; set; }
        public int Brasil { get; set; }
        public int Servia { get; set; }
        public int Suica { get; set; }
        public int Camaroes { get; set; }
        public int BrasilPontos { get; set; }
        public int ServiaPontos { get; set; }
        public int SuicaPontos { get; set; }
        public int CamaroesPontos { get; set; }
        public int BelgicaPontos { get; set; }
        public int CanadaPontos { get; set; }
        public int MarrocosPontos { get; set; }
        public int CroaciaPontos { get; set; }
        public int Portugal { get; set; }
        public int Gana { get; set; }
        public int Uruguai { get; set; }
        public int CoreiaDoSul { get; set; }
        public int PortugalPontos { get; set; }
        public int GanaPontos { get; set; }
        public int UruguaiPontos { get; set; }
        public int CoreiaDoSulPontos { get; set; }
        public string Jogo1 { get; set; }
        public string Jogo2 { get; set; }
        public string Jogo3 { get; set; }
        public string Oitavas { get; set; }
        public string Quartas { get; set; }
        public string Semis { get; set; }
        public string Final { get; set; }
        public string OitavasTime1 { get; set; }
        public string OitavasTime2 { get; set; }
        public string OitavasTime3 { get; set; }
        public string OitavasTime4 { get; set; }
        public string OitavasTime5 { get; set; }
        public string OitavasTime6 { get; set; }
        public string OitavasTime7 { get; set; }
        public string OitavasTime8 { get; set; }
        public string OitavasTime9 { get; set; }
        public string OitavasTime10 { get; set; }
        public string OitavasTime11 { get; set; }
        public string OitavasTime12 { get; set; }
        public string OitavasTime13 { get; set; }
        public string OitavasTime14 { get; set; }
        public string OitavasTime15 { get; set; }
        public string OitavasTime16 { get; set; }
        public string QuartasTime1 { get; set; }
        public string QuartasTime2 { get; set; }
        public string QuartasTime3 { get; set; }
        public string QuartasTime4 { get; set; }
        public string QuartasTime5 { get; set; }
        public string QuartasTime6 { get; set; }
        public string QuartasTime7 { get; set; }
        public string QuartasTime8 { get; set; }
        public string SemisTime1 { get; set; }
        public string SemisTime2 { get; set; }
        public string SemisTime3 { get; set; }
        public string SemisTime4 { get; set; }
        public string FinaisTime1 { get; set; }
        public string FinaisTime2 { get; set; }
        public string Campeao { get; set; }

    }
}
